In [1]:
import pandas as pd

# 1. 데이터 불러오기

In [6]:
data = pd.read_csv('./hand_data.csv', header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.708618,0.726508,4.931828e-07,0.651716,0.728453,-0.023138,0.596217,0.684290,-0.037493,0.581995,...,0.662557,0.480840,-0.072301,0.656634,0.527027,-0.071040,0.658847,0.574724,-0.064453,Sissors
1,0.704302,0.726838,4.915186e-07,0.648160,0.728611,-0.022461,0.592547,0.685299,-0.036726,0.577028,...,0.659084,0.484208,-0.072856,0.652843,0.530745,-0.071304,0.654971,0.578574,-0.064600,Sissors
2,0.684500,0.742820,5.485762e-07,0.627028,0.733941,-0.024318,0.576412,0.682249,-0.040027,0.571010,...,0.669921,0.495559,-0.077260,0.661319,0.544758,-0.074871,0.659839,0.594656,-0.066984,Sissors
3,0.663071,0.734723,5.286115e-07,0.603253,0.728509,-0.020485,0.553365,0.680227,-0.034699,0.532234,...,0.611850,0.502989,-0.072672,0.598922,0.550589,-0.072001,0.598820,0.596124,-0.065440,Sissors
4,0.676052,0.722018,4.886666e-07,0.618586,0.726268,-0.018217,0.561764,0.690471,-0.031905,0.537742,...,0.600835,0.496626,-0.070187,0.594168,0.539570,-0.067543,0.600146,0.583500,-0.059988,Sissors

In [7]:
# 컬럼 이름 바꾸기
# 열 개수: 64 (=21 개 * 3(XYZ) + 1 label)
columns = []
for i in range(21):
    columns.extend([f'x{i+1}', f'y{i+1}', f'z{i+1}'])
columns.append('label')

print(len(columns))
print(columns)

64
['x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3', 'x4', 'y4', 'z4', 'x5', 'y5', 'z5', 'x6', 'y6', 'z6', 'x7', 'y7', 'z7', 'x8', 'y8', 'z8', 'x9', 'y9', 'z9', 'x10', 'y10', 'z10', 'x11', 'y11', 'z11', 'x12', 'y12', 'z12', 'x13', 'y13', 'z13', 'x14', 'y14', 'z14', 'x15', 'y15', 'z15', 'x16', 'y16', 'z16', 'x17', 'y17', 'z17', 'x18', 'y18', 'z18', 'x19', 'y19', 'z19', 'x20', 'y20', 'z20', 'x21', 'y21', 'z21', 'label']

In [9]:
data.columns = columns 
data.head(1)

,x1,y1,z1,x2,y2,z2,x3,y3,z3,x4,...,x19,y19,z19,x20,y20,z20,x21,y21,z21,label
0,0.708618,0.726508,4.931828e-07,0.651716,0.728453,-0.023138,0.596217,0.68429,-0.037493,0.581995,...,0.662557,0.48084,-0.072301,0.656634,0.527027,-0.07104,0.658847,0.574724,-0.064453,Sissors

# 2. 데이터 분할하기

In [10]:
def encoding(label):
    if label == 'Sissors':
        return 0
    elif label == 'Rock':
        return 1
    elif label == 'Paper':
        return 2
    else:
        return -1

data["label_enc"] = data['label'].apply(lambda x: encoding(x))
data.head(2)

,x1,y1,z1,x2,y2,z2,x3,y3,z3,x4,...,y19,z19,x20,y20,z20,x21,y21,z21,label,label_enc
0,0.708618,0.726508,4.931828e-07,0.651716,0.728453,-0.023138,0.596217,0.684290,-0.037493,0.581995,...,0.480840,-0.072301,0.656634,0.527027,-0.071040,0.658847,0.574724,-0.064453,Sissors,0
1,0.704302,0.726838,4.915186e-07,0.648160,0.728611,-0.022461,0.592547,0.685299,-0.036726,0.577028,...,0.484208,-0.072856,0.652843,0.530745,-0.071304,0.654971,0.578574,-0.064600,Sissors,0

In [11]:
# X, y
X = data.iloc[:, :-2]
y = data['label_enc']
print(X.shape, y.shape)

(742, 63) (742,)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True, stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(593, 63) (149, 63) (593,) (149,)

# 3. 모델 학습

In [14]:
# uv add xgboost
from xgboost import XGBClassifier 
import numpy as np 

model = XGBClassifier(n_estimators=10, random_state=42)
model.fit(np.array(X_train), np.array(y_train))

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=10,
              n_jobs=None, num_parallel_tree=None, ...)

# 4. 모델 성능 평가

In [15]:
from sklearn.metrics import classification_report 

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        39
           1       1.00      1.00      1.00        50
           2       0.98      0.98      0.98        60

    accuracy                           0.99       149
   macro avg       0.99      0.99      0.99       149
weighted avg       0.99      0.99      0.99       149

# 5. 모델 내보내기

In [16]:
import joblib 

joblib.dump(model, "./scissors_rock_paper.pkl")

['./scissors_rock_paper.pkl']

In [17]:
# 모델 다시 불러올때에는?
import joblib 

model = joblib.load("./scissors_rock_paper.pkl")
model

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=10,
              n_jobs=None, num_parallel_tree=None, ...)